// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Copy.proto

#ifndef PROTOBUF_Msg_5fCopy_2eproto__INCLUDED
#define PROTOBUF_Msg_5fCopy_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Msg_5fCopy_2eproto();
void protobuf_AssignDesc_Msg_5fCopy_2eproto();
void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

class BattleResultNty;
class ItemData;
class MainCopyAck;
class MainCopyReq;
class MainCopyResultNty;
class Msg_BroadRoomNotify;
class Msg_CreateRoomAck;
class Msg_CreateRoomReq;
class Msg_JoinRoomAck;
class Msg_JoinRoomReq;
class Msg_KickRoomAck;
class Msg_KickRoomReq;
class Msg_LeaveRoomAck;
class Msg_LeaveRoomReq;
class Msg_RoomPlayerInfo;
class Msg_StartRoomAck;
class Msg_StartRoomReq;
class ResultObject;
class ResultPlayer;

// ===================================================================

class ResultObject : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ResultObject) */ {
 public:
  ResultObject();
  virtual ~ResultObject();

  ResultObject(const ResultObject& from);

  inline ResultObject& operator=(const ResultObject& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultObject& default_instance();

  void Swap(ResultObject* other);

  // implements Message ----------------------------------------------

  inline ResultObject* New() const { return New(NULL); }

  ResultObject* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultObject& from);
  void MergeFrom(const ResultObject& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResultObject* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 ObjectID = 1;
  void clear_objectid();
  static const int kObjectIDFieldNumber = 1;
  ::google::protobuf::uint64 objectid() const;
  void set_objectid(::google::protobuf::uint64 value);

  // optional int32 ActorID = 2;
  void clear_actorid();
  static const int kActorIDFieldNumber = 2;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // optional int32 ObjectType = 3;
  void clear_objecttype();
  static const int kObjectTypeFieldNumber = 3;
  ::google::protobuf::int32 objecttype() const;
  void set_objecttype(::google::protobuf::int32 value);

  // optional int32 Result = 4;
  void clear_result();
  static const int kResultFieldNumber = 4;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // optional int32 Kill = 5;
  void clear_kill();
  static const int kKillFieldNumber = 5;
  ::google::protobuf::int32 kill() const;
  void set_kill(::google::protobuf::int32 value);

  // optional int32 Death = 6;
  void clear_death();
  static const int kDeathFieldNumber = 6;
  ::google::protobuf::int32 death() const;
  void set_death(::google::protobuf::int32 value);

  // optional int32 Heal = 7;
  void clear_heal();
  static const int kHealFieldNumber = 7;
  ::google::protobuf::int32 heal() const;
  void set_heal(::google::protobuf::int32 value);

  // optional int32 Damage = 8;
  void clear_damage();
  static const int kDamageFieldNumber = 8;
  ::google::protobuf::int32 damage() const;
  void set_damage(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ResultObject)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::int32 objecttype_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 kill_;
  ::google::protobuf::int32 death_;
  ::google::protobuf::int32 heal_;
  ::google::protobuf::int32 damage_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static ResultObject* default_instance_;
};
// -------------------------------------------------------------------

class ResultPlayer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ResultPlayer) */ {
 public:
  ResultPlayer();
  virtual ~ResultPlayer();

  ResultPlayer(const ResultPlayer& from);

  inline ResultPlayer& operator=(const ResultPlayer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResultPlayer& default_instance();

  void Swap(ResultPlayer* other);

  // implements Message ----------------------------------------------

  inline ResultPlayer* New() const { return New(NULL); }

  ResultPlayer* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResultPlayer& from);
  void MergeFrom(const ResultPlayer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ResultPlayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 ObjectID = 1;
  void clear_objectid();
  static const int kObjectIDFieldNumber = 1;
  ::google::protobuf::uint64 objectid() const;
  void set_objectid(::google::protobuf::uint64 value);

  // optional int32 ActorID = 2;
  void clear_actorid();
  static const int kActorIDFieldNumber = 2;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // optional int32 ObjectType = 3;
  void clear_objecttype();
  static const int kObjectTypeFieldNumber = 3;
  ::google::protobuf::int32 objecttype() const;
  void set_objecttype(::google::protobuf::int32 value);

  // optional int32 Result = 4;
  void clear_result();
  static const int kResultFieldNumber = 4;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // optional int32 Kill = 5;
  void clear_kill();
  static const int kKillFieldNumber = 5;
  ::google::protobuf::int32 kill() const;
  void set_kill(::google::protobuf::int32 value);

  // optional int32 Death = 6;
  void clear_death();
  static const int kDeathFieldNumber = 6;
  ::google::protobuf::int32 death() const;
  void set_death(::google::protobuf::int32 value);

  // optional int32 Heal = 7;
  void clear_heal();
  static const int kHealFieldNumber = 7;
  ::google::protobuf::int32 heal() const;
  void set_heal(::google::protobuf::int32 value);

  // optional int32 Damage = 8;
  void clear_damage();
  static const int kDamageFieldNumber = 8;
  ::google::protobuf::int32 damage() const;
  void set_damage(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ResultPlayer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 objectid_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::int32 objecttype_;
  ::google::protobuf::int32 result_;
  ::google::protobuf::int32 kill_;
  ::google::protobuf::int32 death_;
  ::google::protobuf::int32 heal_;
  ::google::protobuf::int32 damage_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static ResultPlayer* default_instance_;
};
// -------------------------------------------------------------------

class BattleResultNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleResultNty) */ {
 public:
  BattleResultNty();
  virtual ~BattleResultNty();

  BattleResultNty(const BattleResultNty& from);

  inline BattleResultNty& operator=(const BattleResultNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleResultNty& default_instance();

  void Swap(BattleResultNty* other);

  // implements Message ----------------------------------------------

  inline BattleResultNty* New() const { return New(NULL); }

  BattleResultNty* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BattleResultNty& from);
  void MergeFrom(const BattleResultNty& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleResultNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ServerID = 1;
  void clear_serverid();
  static const int kServerIDFieldNumber = 1;
  ::google::protobuf::int32 serverid() const;
  void set_serverid(::google::protobuf::int32 value);

  // optional uint32 CopyGuid = 2;
  void clear_copyguid();
  static const int kCopyGuidFieldNumber = 2;
  ::google::protobuf::uint32 copyguid() const;
  void set_copyguid(::google::protobuf::uint32 value);

  // optional int32 CopyID = 3;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 3;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // optional int32 CopyType = 4;
  void clear_copytype();
  static const int kCopyTypeFieldNumber = 4;
  ::google::protobuf::int32 copytype() const;
  void set_copytype(::google::protobuf::int32 value);

  // optional uint64 LastTime = 5;
  void clear_lasttime();
  static const int kLastTimeFieldNumber = 5;
  ::google::protobuf::uint64 lasttime() const;
  void set_lasttime(::google::protobuf::uint64 value);

  // repeated .ResultPlayer PlayerList = 6;
  int playerlist_size() const;
  void clear_playerlist();
  static const int kPlayerListFieldNumber = 6;
  const ::ResultPlayer& playerlist(int index) const;
  ::ResultPlayer* mutable_playerlist(int index);
  ::ResultPlayer* add_playerlist();
  ::google::protobuf::RepeatedPtrField< ::ResultPlayer >*
      mutable_playerlist();
  const ::google::protobuf::RepeatedPtrField< ::ResultPlayer >&
      playerlist() const;

  // repeated .ResultObject ObjectList = 7;
  int objectlist_size() const;
  void clear_objectlist();
  static const int kObjectListFieldNumber = 7;
  const ::ResultObject& objectlist(int index) const;
  ::ResultObject* mutable_objectlist(int index);
  ::ResultObject* add_objectlist();
  ::google::protobuf::RepeatedPtrField< ::ResultObject >*
      mutable_objectlist();
  const ::google::protobuf::RepeatedPtrField< ::ResultObject >&
      objectlist() const;

  // @@protoc_insertion_point(class_scope:BattleResultNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 serverid_;
  ::google::protobuf::uint32 copyguid_;
  ::google::protobuf::int32 copyid_;
  ::google::protobuf::int32 copytype_;
  ::google::protobuf::uint64 lasttime_;
  ::google::protobuf::RepeatedPtrField< ::ResultPlayer > playerlist_;
  ::google::protobuf::RepeatedPtrField< ::ResultObject > objectlist_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static BattleResultNty* default_instance_;
};
// -------------------------------------------------------------------

class MainCopyReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MainCopyReq) */ {
 public:
  MainCopyReq();
  virtual ~MainCopyReq();

  MainCopyReq(const MainCopyReq& from);

  inline MainCopyReq& operator=(const MainCopyReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MainCopyReq& default_instance();

  void Swap(MainCopyReq* other);

  // implements Message ----------------------------------------------

  inline MainCopyReq* New() const { return New(NULL); }

  MainCopyReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MainCopyReq& from);
  void MergeFrom(const MainCopyReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MainCopyReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 CopyID = 1;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 1;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MainCopyReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 copyid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static MainCopyReq* default_instance_;
};
// -------------------------------------------------------------------

class MainCopyAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MainCopyAck) */ {
 public:
  MainCopyAck();
  virtual ~MainCopyAck();

  MainCopyAck(const MainCopyAck& from);

  inline MainCopyAck& operator=(const MainCopyAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MainCopyAck& default_instance();

  void Swap(MainCopyAck* other);

  // implements Message ----------------------------------------------

  inline MainCopyAck* New() const { return New(NULL); }

  MainCopyAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MainCopyAck& from);
  void MergeFrom(const MainCopyAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MainCopyAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:MainCopyAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static MainCopyAck* default_instance_;
};
// -------------------------------------------------------------------

class ItemData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ItemData) */ {
 public:
  ItemData();
  virtual ~ItemData();

  ItemData(const ItemData& from);

  inline ItemData& operator=(const ItemData& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemData& default_instance();

  void Swap(ItemData* other);

  // implements Message ----------------------------------------------

  inline ItemData* New() const { return New(NULL); }

  ItemData* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemData& from);
  void MergeFrom(const ItemData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ItemData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 ItemID = 1;
  void clear_itemid();
  static const int kItemIDFieldNumber = 1;
  ::google::protobuf::int32 itemid() const;
  void set_itemid(::google::protobuf::int32 value);

  // optional int32 ItemNum = 2;
  void clear_itemnum();
  static const int kItemNumFieldNumber = 2;
  ::google::protobuf::int32 itemnum() const;
  void set_itemnum(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ItemData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 itemid_;
  ::google::protobuf::int32 itemnum_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static ItemData* default_instance_;
};
// -------------------------------------------------------------------

class MainCopyResultNty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MainCopyResultNty) */ {
 public:
  MainCopyResultNty();
  virtual ~MainCopyResultNty();

  MainCopyResultNty(const MainCopyResultNty& from);

  inline MainCopyResultNty& operator=(const MainCopyResultNty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MainCopyResultNty& default_instance();

  void Swap(MainCopyResultNty* other);

  // implements Message ----------------------------------------------

  inline MainCopyResultNty* New() const { return New(NULL); }

  MainCopyResultNty* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MainCopyResultNty& from);
  void MergeFrom(const MainCopyResultNty& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MainCopyResultNty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional int32 CopyID = 2;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 2;
  ::google::protobuf::int32 copyid() const;
  void set_copyid(::google::protobuf::int32 value);

  // optional int32 CopyResult = 3;
  void clear_copyresult();
  static const int kCopyResultFieldNumber = 3;
  ::google::protobuf::int32 copyresult() const;
  void set_copyresult(::google::protobuf::int32 value);

  // optional int32 StarNum = 4;
  void clear_starnum();
  static const int kStarNumFieldNumber = 4;
  ::google::protobuf::int32 starnum() const;
  void set_starnum(::google::protobuf::int32 value);

  // optional uint64 LastTime = 5;
  void clear_lasttime();
  static const int kLastTimeFieldNumber = 5;
  ::google::protobuf::uint64 lasttime() const;
  void set_lasttime(::google::protobuf::uint64 value);

  // repeated .ItemData ItemList = 6;
  int itemlist_size() const;
  void clear_itemlist();
  static const int kItemListFieldNumber = 6;
  const ::ItemData& itemlist(int index) const;
  ::ItemData* mutable_itemlist(int index);
  ::ItemData* add_itemlist();
  ::google::protobuf::RepeatedPtrField< ::ItemData >*
      mutable_itemlist();
  const ::google::protobuf::RepeatedPtrField< ::ItemData >&
      itemlist() const;

  // @@protoc_insertion_point(class_scope:MainCopyResultNty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::int32 copyid_;
  ::google::protobuf::int32 copyresult_;
  ::google::protobuf::uint64 lasttime_;
  ::google::protobuf::RepeatedPtrField< ::ItemData > itemlist_;
  ::google::protobuf::int32 starnum_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static MainCopyResultNty* default_instance_;
};
// -------------------------------------------------------------------

class Msg_CreateRoomReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_CreateRoomReq) */ {
 public:
  Msg_CreateRoomReq();
  virtual ~Msg_CreateRoomReq();

  Msg_CreateRoomReq(const Msg_CreateRoomReq& from);

  inline Msg_CreateRoomReq& operator=(const Msg_CreateRoomReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_CreateRoomReq& default_instance();

  void Swap(Msg_CreateRoomReq* other);

  // implements Message ----------------------------------------------

  inline Msg_CreateRoomReq* New() const { return New(NULL); }

  Msg_CreateRoomReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_CreateRoomReq& from);
  void MergeFrom(const Msg_CreateRoomReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_CreateRoomReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional uint32 CopyID = 2;
  void clear_copyid();
  static const int kCopyIDFieldNumber = 2;
  ::google::protobuf::uint32 copyid() const;
  void set_copyid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Msg_CreateRoomReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint32 copyid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_CreateRoomReq* default_instance_;
};
// -------------------------------------------------------------------

class Msg_CreateRoomAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_CreateRoomAck) */ {
 public:
  Msg_CreateRoomAck();
  virtual ~Msg_CreateRoomAck();

  Msg_CreateRoomAck(const Msg_CreateRoomAck& from);

  inline Msg_CreateRoomAck& operator=(const Msg_CreateRoomAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_CreateRoomAck& default_instance();

  void Swap(Msg_CreateRoomAck* other);

  // implements Message ----------------------------------------------

  inline Msg_CreateRoomAck* New() const { return New(NULL); }

  Msg_CreateRoomAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_CreateRoomAck& from);
  void MergeFrom(const Msg_CreateRoomAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_CreateRoomAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_CreateRoomAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roomid_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_CreateRoomAck* default_instance_;
};
// -------------------------------------------------------------------

class Msg_JoinRoomReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_JoinRoomReq) */ {
 public:
  Msg_JoinRoomReq();
  virtual ~Msg_JoinRoomReq();

  Msg_JoinRoomReq(const Msg_JoinRoomReq& from);

  inline Msg_JoinRoomReq& operator=(const Msg_JoinRoomReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_JoinRoomReq& default_instance();

  void Swap(Msg_JoinRoomReq* other);

  // implements Message ----------------------------------------------

  inline Msg_JoinRoomReq* New() const { return New(NULL); }

  Msg_JoinRoomReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_JoinRoomReq& from);
  void MergeFrom(const Msg_JoinRoomReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_JoinRoomReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_JoinRoomReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint64 roomid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_JoinRoomReq* default_instance_;
};
// -------------------------------------------------------------------

class Msg_JoinRoomAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_JoinRoomAck) */ {
 public:
  Msg_JoinRoomAck();
  virtual ~Msg_JoinRoomAck();

  Msg_JoinRoomAck(const Msg_JoinRoomAck& from);

  inline Msg_JoinRoomAck& operator=(const Msg_JoinRoomAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_JoinRoomAck& default_instance();

  void Swap(Msg_JoinRoomAck* other);

  // implements Message ----------------------------------------------

  inline Msg_JoinRoomAck* New() const { return New(NULL); }

  Msg_JoinRoomAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_JoinRoomAck& from);
  void MergeFrom(const Msg_JoinRoomAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_JoinRoomAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_JoinRoomAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roomid_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_JoinRoomAck* default_instance_;
};
// -------------------------------------------------------------------

class Msg_KickRoomReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_KickRoomReq) */ {
 public:
  Msg_KickRoomReq();
  virtual ~Msg_KickRoomReq();

  Msg_KickRoomReq(const Msg_KickRoomReq& from);

  inline Msg_KickRoomReq& operator=(const Msg_KickRoomReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_KickRoomReq& default_instance();

  void Swap(Msg_KickRoomReq* other);

  // implements Message ----------------------------------------------

  inline Msg_KickRoomReq* New() const { return New(NULL); }

  Msg_KickRoomReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_KickRoomReq& from);
  void MergeFrom(const Msg_KickRoomReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_KickRoomReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_KickRoomReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint64 roomid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_KickRoomReq* default_instance_;
};
// -------------------------------------------------------------------

class Msg_KickRoomAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_KickRoomAck) */ {
 public:
  Msg_KickRoomAck();
  virtual ~Msg_KickRoomAck();

  Msg_KickRoomAck(const Msg_KickRoomAck& from);

  inline Msg_KickRoomAck& operator=(const Msg_KickRoomAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_KickRoomAck& default_instance();

  void Swap(Msg_KickRoomAck* other);

  // implements Message ----------------------------------------------

  inline Msg_KickRoomAck* New() const { return New(NULL); }

  Msg_KickRoomAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_KickRoomAck& from);
  void MergeFrom(const Msg_KickRoomAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_KickRoomAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Msg_KickRoomAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_KickRoomAck* default_instance_;
};
// -------------------------------------------------------------------

class Msg_LeaveRoomReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_LeaveRoomReq) */ {
 public:
  Msg_LeaveRoomReq();
  virtual ~Msg_LeaveRoomReq();

  Msg_LeaveRoomReq(const Msg_LeaveRoomReq& from);

  inline Msg_LeaveRoomReq& operator=(const Msg_LeaveRoomReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_LeaveRoomReq& default_instance();

  void Swap(Msg_LeaveRoomReq* other);

  // implements Message ----------------------------------------------

  inline Msg_LeaveRoomReq* New() const { return New(NULL); }

  Msg_LeaveRoomReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_LeaveRoomReq& from);
  void MergeFrom(const Msg_LeaveRoomReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_LeaveRoomReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_LeaveRoomReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint64 roomid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_LeaveRoomReq* default_instance_;
};
// -------------------------------------------------------------------

class Msg_LeaveRoomAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_LeaveRoomAck) */ {
 public:
  Msg_LeaveRoomAck();
  virtual ~Msg_LeaveRoomAck();

  Msg_LeaveRoomAck(const Msg_LeaveRoomAck& from);

  inline Msg_LeaveRoomAck& operator=(const Msg_LeaveRoomAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_LeaveRoomAck& default_instance();

  void Swap(Msg_LeaveRoomAck* other);

  // implements Message ----------------------------------------------

  inline Msg_LeaveRoomAck* New() const { return New(NULL); }

  Msg_LeaveRoomAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_LeaveRoomAck& from);
  void MergeFrom(const Msg_LeaveRoomAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_LeaveRoomAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Msg_LeaveRoomAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_LeaveRoomAck* default_instance_;
};
// -------------------------------------------------------------------

class Msg_StartRoomReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_StartRoomReq) */ {
 public:
  Msg_StartRoomReq();
  virtual ~Msg_StartRoomReq();

  Msg_StartRoomReq(const Msg_StartRoomReq& from);

  inline Msg_StartRoomReq& operator=(const Msg_StartRoomReq& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_StartRoomReq& default_instance();

  void Swap(Msg_StartRoomReq* other);

  // implements Message ----------------------------------------------

  inline Msg_StartRoomReq* New() const { return New(NULL); }

  Msg_StartRoomReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_StartRoomReq& from);
  void MergeFrom(const Msg_StartRoomReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_StartRoomReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional uint64 RoomID = 2;
  void clear_roomid();
  static const int kRoomIDFieldNumber = 2;
  ::google::protobuf::uint64 roomid() const;
  void set_roomid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:Msg_StartRoomReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::uint64 roomid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_StartRoomReq* default_instance_;
};
// -------------------------------------------------------------------

class Msg_StartRoomAck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_StartRoomAck) */ {
 public:
  Msg_StartRoomAck();
  virtual ~Msg_StartRoomAck();

  Msg_StartRoomAck(const Msg_StartRoomAck& from);

  inline Msg_StartRoomAck& operator=(const Msg_StartRoomAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_StartRoomAck& default_instance();

  void Swap(Msg_StartRoomAck* other);

  // implements Message ----------------------------------------------

  inline Msg_StartRoomAck* New() const { return New(NULL); }

  Msg_StartRoomAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_StartRoomAck& from);
  void MergeFrom(const Msg_StartRoomAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_StartRoomAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 RetCode = 1;
  void clear_retcode();
  static const int kRetCodeFieldNumber = 1;
  ::google::protobuf::uint32 retcode() const;
  void set_retcode(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:Msg_StartRoomAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 retcode_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_StartRoomAck* default_instance_;
};
// -------------------------------------------------------------------

class Msg_RoomPlayerInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_RoomPlayerInfo) */ {
 public:
  Msg_RoomPlayerInfo();
  virtual ~Msg_RoomPlayerInfo();

  Msg_RoomPlayerInfo(const Msg_RoomPlayerInfo& from);

  inline Msg_RoomPlayerInfo& operator=(const Msg_RoomPlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_RoomPlayerInfo& default_instance();

  void Swap(Msg_RoomPlayerInfo* other);

  // implements Message ----------------------------------------------

  inline Msg_RoomPlayerInfo* New() const { return New(NULL); }

  Msg_RoomPlayerInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_RoomPlayerInfo& from);
  void MergeFrom(const Msg_RoomPlayerInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_RoomPlayerInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 RoleID = 1;
  void clear_roleid();
  static const int kRoleIDFieldNumber = 1;
  ::google::protobuf::uint64 roleid() const;
  void set_roleid(::google::protobuf::uint64 value);

  // optional int32 Level = 2;
  void clear_level();
  static const int kLevelFieldNumber = 2;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // optional string Name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 ActorID = 4;
  void clear_actorid();
  static const int kActorIDFieldNumber = 4;
  ::google::protobuf::int32 actorid() const;
  void set_actorid(::google::protobuf::int32 value);

  // optional int32 MountID = 5;
  void clear_mountid();
  static const int kMountIDFieldNumber = 5;
  ::google::protobuf::int32 mountid() const;
  void set_mountid(::google::protobuf::int32 value);

  // repeated int32 Equips = 6;
  int equips_size() const;
  void clear_equips();
  static const int kEquipsFieldNumber = 6;
  ::google::protobuf::int32 equips(int index) const;
  void set_equips(int index, ::google::protobuf::int32 value);
  void add_equips(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      equips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_equips();

  // @@protoc_insertion_point(class_scope:Msg_RoomPlayerInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 roleid_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 actorid_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > equips_;
  mutable int _equips_cached_byte_size_;
  ::google::protobuf::int32 mountid_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_RoomPlayerInfo* default_instance_;
};
// -------------------------------------------------------------------

class Msg_BroadRoomNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Msg_BroadRoomNotify) */ {
 public:
  Msg_BroadRoomNotify();
  virtual ~Msg_BroadRoomNotify();

  Msg_BroadRoomNotify(const Msg_BroadRoomNotify& from);

  inline Msg_BroadRoomNotify& operator=(const Msg_BroadRoomNotify& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Msg_BroadRoomNotify& default_instance();

  void Swap(Msg_BroadRoomNotify* other);

  // implements Message ----------------------------------------------

  inline Msg_BroadRoomNotify* New() const { return New(NULL); }

  Msg_BroadRoomNotify* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Msg_BroadRoomNotify& from);
  void MergeFrom(const Msg_BroadRoomNotify& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Msg_BroadRoomNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Msg_RoomPlayerInfo PlayerList = 1;
  int playerlist_size() const;
  void clear_playerlist();
  static const int kPlayerListFieldNumber = 1;
  const ::Msg_RoomPlayerInfo& playerlist(int index) const;
  ::Msg_RoomPlayerInfo* mutable_playerlist(int index);
  ::Msg_RoomPlayerInfo* add_playerlist();
  ::google::protobuf::RepeatedPtrField< ::Msg_RoomPlayerInfo >*
      mutable_playerlist();
  const ::google::protobuf::RepeatedPtrField< ::Msg_RoomPlayerInfo >&
      playerlist() const;

  // @@protoc_insertion_point(class_scope:Msg_BroadRoomNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::Msg_RoomPlayerInfo > playerlist_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_Msg_5fCopy_2eproto();
  friend void protobuf_AssignDesc_Msg_5fCopy_2eproto();
  friend void protobuf_ShutdownFile_Msg_5fCopy_2eproto();

  void InitAsDefaultInstance();
  static Msg_BroadRoomNotify* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ResultObject

// optional uint64 ObjectID = 1;
inline void ResultObject::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ResultObject::objectid() const {
  // @@protoc_insertion_point(field_get:ResultObject.ObjectID)
  return objectid_;
}
inline void ResultObject::set_objectid(::google::protobuf::uint64 value) {
  
  objectid_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.ObjectID)
}

// optional int32 ActorID = 2;
inline void ResultObject::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 ResultObject::actorid() const {
  // @@protoc_insertion_point(field_get:ResultObject.ActorID)
  return actorid_;
}
inline void ResultObject::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.ActorID)
}

// optional int32 ObjectType = 3;
inline void ResultObject::clear_objecttype() {
  objecttype_ = 0;
}
inline ::google::protobuf::int32 ResultObject::objecttype() const {
  // @@protoc_insertion_point(field_get:ResultObject.ObjectType)
  return objecttype_;
}
inline void ResultObject::set_objecttype(::google::protobuf::int32 value) {
  
  objecttype_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.ObjectType)
}

// optional int32 Result = 4;
inline void ResultObject::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 ResultObject::result() const {
  // @@protoc_insertion_point(field_get:ResultObject.Result)
  return result_;
}
inline void ResultObject::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.Result)
}

// optional int32 Kill = 5;
inline void ResultObject::clear_kill() {
  kill_ = 0;
}
inline ::google::protobuf::int32 ResultObject::kill() const {
  // @@protoc_insertion_point(field_get:ResultObject.Kill)
  return kill_;
}
inline void ResultObject::set_kill(::google::protobuf::int32 value) {
  
  kill_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.Kill)
}

// optional int32 Death = 6;
inline void ResultObject::clear_death() {
  death_ = 0;
}
inline ::google::protobuf::int32 ResultObject::death() const {
  // @@protoc_insertion_point(field_get:ResultObject.Death)
  return death_;
}
inline void ResultObject::set_death(::google::protobuf::int32 value) {
  
  death_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.Death)
}

// optional int32 Heal = 7;
inline void ResultObject::clear_heal() {
  heal_ = 0;
}
inline ::google::protobuf::int32 ResultObject::heal() const {
  // @@protoc_insertion_point(field_get:ResultObject.Heal)
  return heal_;
}
inline void ResultObject::set_heal(::google::protobuf::int32 value) {
  
  heal_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.Heal)
}

// optional int32 Damage = 8;
inline void ResultObject::clear_damage() {
  damage_ = 0;
}
inline ::google::protobuf::int32 ResultObject::damage() const {
  // @@protoc_insertion_point(field_get:ResultObject.Damage)
  return damage_;
}
inline void ResultObject::set_damage(::google::protobuf::int32 value) {
  
  damage_ = value;
  // @@protoc_insertion_point(field_set:ResultObject.Damage)
}

// -------------------------------------------------------------------

// ResultPlayer

// optional uint64 ObjectID = 1;
inline void ResultPlayer::clear_objectid() {
  objectid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ResultPlayer::objectid() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.ObjectID)
  return objectid_;
}
inline void ResultPlayer::set_objectid(::google::protobuf::uint64 value) {
  
  objectid_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.ObjectID)
}

// optional int32 ActorID = 2;
inline void ResultPlayer::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::actorid() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.ActorID)
  return actorid_;
}
inline void ResultPlayer::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.ActorID)
}

// optional int32 ObjectType = 3;
inline void ResultPlayer::clear_objecttype() {
  objecttype_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::objecttype() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.ObjectType)
  return objecttype_;
}
inline void ResultPlayer::set_objecttype(::google::protobuf::int32 value) {
  
  objecttype_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.ObjectType)
}

// optional int32 Result = 4;
inline void ResultPlayer::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::result() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.Result)
  return result_;
}
inline void ResultPlayer::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.Result)
}

// optional int32 Kill = 5;
inline void ResultPlayer::clear_kill() {
  kill_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::kill() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.Kill)
  return kill_;
}
inline void ResultPlayer::set_kill(::google::protobuf::int32 value) {
  
  kill_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.Kill)
}

// optional int32 Death = 6;
inline void ResultPlayer::clear_death() {
  death_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::death() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.Death)
  return death_;
}
inline void ResultPlayer::set_death(::google::protobuf::int32 value) {
  
  death_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.Death)
}

// optional int32 Heal = 7;
inline void ResultPlayer::clear_heal() {
  heal_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::heal() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.Heal)
  return heal_;
}
inline void ResultPlayer::set_heal(::google::protobuf::int32 value) {
  
  heal_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.Heal)
}

// optional int32 Damage = 8;
inline void ResultPlayer::clear_damage() {
  damage_ = 0;
}
inline ::google::protobuf::int32 ResultPlayer::damage() const {
  // @@protoc_insertion_point(field_get:ResultPlayer.Damage)
  return damage_;
}
inline void ResultPlayer::set_damage(::google::protobuf::int32 value) {
  
  damage_ = value;
  // @@protoc_insertion_point(field_set:ResultPlayer.Damage)
}

// -------------------------------------------------------------------

// BattleResultNty

// optional int32 ServerID = 1;
inline void BattleResultNty::clear_serverid() {
  serverid_ = 0;
}
inline ::google::protobuf::int32 BattleResultNty::serverid() const {
  // @@protoc_insertion_point(field_get:BattleResultNty.ServerID)
  return serverid_;
}
inline void BattleResultNty::set_serverid(::google::protobuf::int32 value) {
  
  serverid_ = value;
  // @@protoc_insertion_point(field_set:BattleResultNty.ServerID)
}

// optional uint32 CopyGuid = 2;
inline void BattleResultNty::clear_copyguid() {
  copyguid_ = 0u;
}
inline ::google::protobuf::uint32 BattleResultNty::copyguid() const {
  // @@protoc_insertion_point(field_get:BattleResultNty.CopyGuid)
  return copyguid_;
}
inline void BattleResultNty::set_copyguid(::google::protobuf::uint32 value) {
  
  copyguid_ = value;
  // @@protoc_insertion_point(field_set:BattleResultNty.CopyGuid)
}

// optional int32 CopyID = 3;
inline void BattleResultNty::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 BattleResultNty::copyid() const {
  // @@protoc_insertion_point(field_get:BattleResultNty.CopyID)
  return copyid_;
}
inline void BattleResultNty::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:BattleResultNty.CopyID)
}

// optional int32 CopyType = 4;
inline void BattleResultNty::clear_copytype() {
  copytype_ = 0;
}
inline ::google::protobuf::int32 BattleResultNty::copytype() const {
  // @@protoc_insertion_point(field_get:BattleResultNty.CopyType)
  return copytype_;
}
inline void BattleResultNty::set_copytype(::google::protobuf::int32 value) {
  
  copytype_ = value;
  // @@protoc_insertion_point(field_set:BattleResultNty.CopyType)
}

// optional uint64 LastTime = 5;
inline void BattleResultNty::clear_lasttime() {
  lasttime_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 BattleResultNty::lasttime() const {
  // @@protoc_insertion_point(field_get:BattleResultNty.LastTime)
  return lasttime_;
}
inline void BattleResultNty::set_lasttime(::google::protobuf::uint64 value) {
  
  lasttime_ = value;
  // @@protoc_insertion_point(field_set:BattleResultNty.LastTime)
}

// repeated .ResultPlayer PlayerList = 6;
inline int BattleResultNty::playerlist_size() const {
  return playerlist_.size();
}
inline void BattleResultNty::clear_playerlist() {
  playerlist_.Clear();
}
inline const ::ResultPlayer& BattleResultNty::playerlist(int index) const {
  // @@protoc_insertion_point(field_get:BattleResultNty.PlayerList)
  return playerlist_.Get(index);
}
inline ::ResultPlayer* BattleResultNty::mutable_playerlist(int index) {
  // @@protoc_insertion_point(field_mutable:BattleResultNty.PlayerList)
  return playerlist_.Mutable(index);
}
inline ::ResultPlayer* BattleResultNty::add_playerlist() {
  // @@protoc_insertion_point(field_add:BattleResultNty.PlayerList)
  return playerlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ResultPlayer >*
BattleResultNty::mutable_playerlist() {
  // @@protoc_insertion_point(field_mutable_list:BattleResultNty.PlayerList)
  return &playerlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ResultPlayer >&
BattleResultNty::playerlist() const {
  // @@protoc_insertion_point(field_list:BattleResultNty.PlayerList)
  return playerlist_;
}

// repeated .ResultObject ObjectList = 7;
inline int BattleResultNty::objectlist_size() const {
  return objectlist_.size();
}
inline void BattleResultNty::clear_objectlist() {
  objectlist_.Clear();
}
inline const ::ResultObject& BattleResultNty::objectlist(int index) const {
  // @@protoc_insertion_point(field_get:BattleResultNty.ObjectList)
  return objectlist_.Get(index);
}
inline ::ResultObject* BattleResultNty::mutable_objectlist(int index) {
  // @@protoc_insertion_point(field_mutable:BattleResultNty.ObjectList)
  return objectlist_.Mutable(index);
}
inline ::ResultObject* BattleResultNty::add_objectlist() {
  // @@protoc_insertion_point(field_add:BattleResultNty.ObjectList)
  return objectlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ResultObject >*
BattleResultNty::mutable_objectlist() {
  // @@protoc_insertion_point(field_mutable_list:BattleResultNty.ObjectList)
  return &objectlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ResultObject >&
BattleResultNty::objectlist() const {
  // @@protoc_insertion_point(field_list:BattleResultNty.ObjectList)
  return objectlist_;
}

// -------------------------------------------------------------------

// MainCopyReq

// optional int32 CopyID = 1;
inline void MainCopyReq::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 MainCopyReq::copyid() const {
  // @@protoc_insertion_point(field_get:MainCopyReq.CopyID)
  return copyid_;
}
inline void MainCopyReq::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:MainCopyReq.CopyID)
}

// -------------------------------------------------------------------

// MainCopyAck

// optional uint32 RetCode = 1;
inline void MainCopyAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 MainCopyAck::retcode() const {
  // @@protoc_insertion_point(field_get:MainCopyAck.RetCode)
  return retcode_;
}
inline void MainCopyAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:MainCopyAck.RetCode)
}

// -------------------------------------------------------------------

// ItemData

// optional int32 ItemID = 1;
inline void ItemData::clear_itemid() {
  itemid_ = 0;
}
inline ::google::protobuf::int32 ItemData::itemid() const {
  // @@protoc_insertion_point(field_get:ItemData.ItemID)
  return itemid_;
}
inline void ItemData::set_itemid(::google::protobuf::int32 value) {
  
  itemid_ = value;
  // @@protoc_insertion_point(field_set:ItemData.ItemID)
}

// optional int32 ItemNum = 2;
inline void ItemData::clear_itemnum() {
  itemnum_ = 0;
}
inline ::google::protobuf::int32 ItemData::itemnum() const {
  // @@protoc_insertion_point(field_get:ItemData.ItemNum)
  return itemnum_;
}
inline void ItemData::set_itemnum(::google::protobuf::int32 value) {
  
  itemnum_ = value;
  // @@protoc_insertion_point(field_set:ItemData.ItemNum)
}

// -------------------------------------------------------------------

// MainCopyResultNty

// optional uint64 RoleID = 1;
inline void MainCopyResultNty::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MainCopyResultNty::roleid() const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.RoleID)
  return roleid_;
}
inline void MainCopyResultNty::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:MainCopyResultNty.RoleID)
}

// optional int32 CopyID = 2;
inline void MainCopyResultNty::clear_copyid() {
  copyid_ = 0;
}
inline ::google::protobuf::int32 MainCopyResultNty::copyid() const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.CopyID)
  return copyid_;
}
inline void MainCopyResultNty::set_copyid(::google::protobuf::int32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:MainCopyResultNty.CopyID)
}

// optional int32 CopyResult = 3;
inline void MainCopyResultNty::clear_copyresult() {
  copyresult_ = 0;
}
inline ::google::protobuf::int32 MainCopyResultNty::copyresult() const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.CopyResult)
  return copyresult_;
}
inline void MainCopyResultNty::set_copyresult(::google::protobuf::int32 value) {
  
  copyresult_ = value;
  // @@protoc_insertion_point(field_set:MainCopyResultNty.CopyResult)
}

// optional int32 StarNum = 4;
inline void MainCopyResultNty::clear_starnum() {
  starnum_ = 0;
}
inline ::google::protobuf::int32 MainCopyResultNty::starnum() const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.StarNum)
  return starnum_;
}
inline void MainCopyResultNty::set_starnum(::google::protobuf::int32 value) {
  
  starnum_ = value;
  // @@protoc_insertion_point(field_set:MainCopyResultNty.StarNum)
}

// optional uint64 LastTime = 5;
inline void MainCopyResultNty::clear_lasttime() {
  lasttime_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 MainCopyResultNty::lasttime() const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.LastTime)
  return lasttime_;
}
inline void MainCopyResultNty::set_lasttime(::google::protobuf::uint64 value) {
  
  lasttime_ = value;
  // @@protoc_insertion_point(field_set:MainCopyResultNty.LastTime)
}

// repeated .ItemData ItemList = 6;
inline int MainCopyResultNty::itemlist_size() const {
  return itemlist_.size();
}
inline void MainCopyResultNty::clear_itemlist() {
  itemlist_.Clear();
}
inline const ::ItemData& MainCopyResultNty::itemlist(int index) const {
  // @@protoc_insertion_point(field_get:MainCopyResultNty.ItemList)
  return itemlist_.Get(index);
}
inline ::ItemData* MainCopyResultNty::mutable_itemlist(int index) {
  // @@protoc_insertion_point(field_mutable:MainCopyResultNty.ItemList)
  return itemlist_.Mutable(index);
}
inline ::ItemData* MainCopyResultNty::add_itemlist() {
  // @@protoc_insertion_point(field_add:MainCopyResultNty.ItemList)
  return itemlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ItemData >*
MainCopyResultNty::mutable_itemlist() {
  // @@protoc_insertion_point(field_mutable_list:MainCopyResultNty.ItemList)
  return &itemlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ItemData >&
MainCopyResultNty::itemlist() const {
  // @@protoc_insertion_point(field_list:MainCopyResultNty.ItemList)
  return itemlist_;
}

// -------------------------------------------------------------------

// Msg_CreateRoomReq

// optional uint64 RoleID = 1;
inline void Msg_CreateRoomReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_CreateRoomReq::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_CreateRoomReq.RoleID)
  return roleid_;
}
inline void Msg_CreateRoomReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreateRoomReq.RoleID)
}

// optional uint32 CopyID = 2;
inline void Msg_CreateRoomReq::clear_copyid() {
  copyid_ = 0u;
}
inline ::google::protobuf::uint32 Msg_CreateRoomReq::copyid() const {
  // @@protoc_insertion_point(field_get:Msg_CreateRoomReq.CopyID)
  return copyid_;
}
inline void Msg_CreateRoomReq::set_copyid(::google::protobuf::uint32 value) {
  
  copyid_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreateRoomReq.CopyID)
}

// -------------------------------------------------------------------

// Msg_CreateRoomAck

// optional uint32 RetCode = 1;
inline void Msg_CreateRoomAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 Msg_CreateRoomAck::retcode() const {
  // @@protoc_insertion_point(field_get:Msg_CreateRoomAck.RetCode)
  return retcode_;
}
inline void Msg_CreateRoomAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreateRoomAck.RetCode)
}

// optional uint64 RoomID = 2;
inline void Msg_CreateRoomAck::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_CreateRoomAck::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_CreateRoomAck.RoomID)
  return roomid_;
}
inline void Msg_CreateRoomAck::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_CreateRoomAck.RoomID)
}

// -------------------------------------------------------------------

// Msg_JoinRoomReq

// optional uint64 RoleID = 1;
inline void Msg_JoinRoomReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_JoinRoomReq::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_JoinRoomReq.RoleID)
  return roleid_;
}
inline void Msg_JoinRoomReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_JoinRoomReq.RoleID)
}

// optional uint64 RoomID = 2;
inline void Msg_JoinRoomReq::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_JoinRoomReq::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_JoinRoomReq.RoomID)
  return roomid_;
}
inline void Msg_JoinRoomReq::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_JoinRoomReq.RoomID)
}

// -------------------------------------------------------------------

// Msg_JoinRoomAck

// optional uint32 RetCode = 1;
inline void Msg_JoinRoomAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 Msg_JoinRoomAck::retcode() const {
  // @@protoc_insertion_point(field_get:Msg_JoinRoomAck.RetCode)
  return retcode_;
}
inline void Msg_JoinRoomAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:Msg_JoinRoomAck.RetCode)
}

// optional uint64 RoomID = 2;
inline void Msg_JoinRoomAck::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_JoinRoomAck::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_JoinRoomAck.RoomID)
  return roomid_;
}
inline void Msg_JoinRoomAck::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_JoinRoomAck.RoomID)
}

// -------------------------------------------------------------------

// Msg_KickRoomReq

// optional uint64 RoleID = 1;
inline void Msg_KickRoomReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_KickRoomReq::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_KickRoomReq.RoleID)
  return roleid_;
}
inline void Msg_KickRoomReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_KickRoomReq.RoleID)
}

// optional uint64 RoomID = 2;
inline void Msg_KickRoomReq::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_KickRoomReq::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_KickRoomReq.RoomID)
  return roomid_;
}
inline void Msg_KickRoomReq::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_KickRoomReq.RoomID)
}

// -------------------------------------------------------------------

// Msg_KickRoomAck

// optional uint32 RetCode = 1;
inline void Msg_KickRoomAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 Msg_KickRoomAck::retcode() const {
  // @@protoc_insertion_point(field_get:Msg_KickRoomAck.RetCode)
  return retcode_;
}
inline void Msg_KickRoomAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:Msg_KickRoomAck.RetCode)
}

// -------------------------------------------------------------------

// Msg_LeaveRoomReq

// optional uint64 RoleID = 1;
inline void Msg_LeaveRoomReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_LeaveRoomReq::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_LeaveRoomReq.RoleID)
  return roleid_;
}
inline void Msg_LeaveRoomReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_LeaveRoomReq.RoleID)
}

// optional uint64 RoomID = 2;
inline void Msg_LeaveRoomReq::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_LeaveRoomReq::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_LeaveRoomReq.RoomID)
  return roomid_;
}
inline void Msg_LeaveRoomReq::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_LeaveRoomReq.RoomID)
}

// -------------------------------------------------------------------

// Msg_LeaveRoomAck

// optional uint32 RetCode = 1;
inline void Msg_LeaveRoomAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 Msg_LeaveRoomAck::retcode() const {
  // @@protoc_insertion_point(field_get:Msg_LeaveRoomAck.RetCode)
  return retcode_;
}
inline void Msg_LeaveRoomAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:Msg_LeaveRoomAck.RetCode)
}

// -------------------------------------------------------------------

// Msg_StartRoomReq

// optional uint64 RoleID = 1;
inline void Msg_StartRoomReq::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_StartRoomReq::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_StartRoomReq.RoleID)
  return roleid_;
}
inline void Msg_StartRoomReq::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_StartRoomReq.RoleID)
}

// optional uint64 RoomID = 2;
inline void Msg_StartRoomReq::clear_roomid() {
  roomid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_StartRoomReq::roomid() const {
  // @@protoc_insertion_point(field_get:Msg_StartRoomReq.RoomID)
  return roomid_;
}
inline void Msg_StartRoomReq::set_roomid(::google::protobuf::uint64 value) {
  
  roomid_ = value;
  // @@protoc_insertion_point(field_set:Msg_StartRoomReq.RoomID)
}

// -------------------------------------------------------------------

// Msg_StartRoomAck

// optional uint32 RetCode = 1;
inline void Msg_StartRoomAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::google::protobuf::uint32 Msg_StartRoomAck::retcode() const {
  // @@protoc_insertion_point(field_get:Msg_StartRoomAck.RetCode)
  return retcode_;
}
inline void Msg_StartRoomAck::set_retcode(::google::protobuf::uint32 value) {
  
  retcode_ = value;
  // @@protoc_insertion_point(field_set:Msg_StartRoomAck.RetCode)
}

// -------------------------------------------------------------------

// Msg_RoomPlayerInfo

// optional uint64 RoleID = 1;
inline void Msg_RoomPlayerInfo::clear_roleid() {
  roleid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Msg_RoomPlayerInfo::roleid() const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.RoleID)
  return roleid_;
}
inline void Msg_RoomPlayerInfo::set_roleid(::google::protobuf::uint64 value) {
  
  roleid_ = value;
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.RoleID)
}

// optional int32 Level = 2;
inline void Msg_RoomPlayerInfo::clear_level() {
  level_ = 0;
}
inline ::google::protobuf::int32 Msg_RoomPlayerInfo::level() const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.Level)
  return level_;
}
inline void Msg_RoomPlayerInfo::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.Level)
}

// optional string Name = 3;
inline void Msg_RoomPlayerInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Msg_RoomPlayerInfo::name() const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.Name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Msg_RoomPlayerInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.Name)
}
inline void Msg_RoomPlayerInfo::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Msg_RoomPlayerInfo.Name)
}
inline void Msg_RoomPlayerInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Msg_RoomPlayerInfo.Name)
}
inline ::std::string* Msg_RoomPlayerInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Msg_RoomPlayerInfo.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Msg_RoomPlayerInfo::release_name() {
  // @@protoc_insertion_point(field_release:Msg_RoomPlayerInfo.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Msg_RoomPlayerInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Msg_RoomPlayerInfo.Name)
}

// optional int32 ActorID = 4;
inline void Msg_RoomPlayerInfo::clear_actorid() {
  actorid_ = 0;
}
inline ::google::protobuf::int32 Msg_RoomPlayerInfo::actorid() const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.ActorID)
  return actorid_;
}
inline void Msg_RoomPlayerInfo::set_actorid(::google::protobuf::int32 value) {
  
  actorid_ = value;
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.ActorID)
}

// optional int32 MountID = 5;
inline void Msg_RoomPlayerInfo::clear_mountid() {
  mountid_ = 0;
}
inline ::google::protobuf::int32 Msg_RoomPlayerInfo::mountid() const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.MountID)
  return mountid_;
}
inline void Msg_RoomPlayerInfo::set_mountid(::google::protobuf::int32 value) {
  
  mountid_ = value;
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.MountID)
}

// repeated int32 Equips = 6;
inline int Msg_RoomPlayerInfo::equips_size() const {
  return equips_.size();
}
inline void Msg_RoomPlayerInfo::clear_equips() {
  equips_.Clear();
}
inline ::google::protobuf::int32 Msg_RoomPlayerInfo::equips(int index) const {
  // @@protoc_insertion_point(field_get:Msg_RoomPlayerInfo.Equips)
  return equips_.Get(index);
}
inline void Msg_RoomPlayerInfo::set_equips(int index, ::google::protobuf::int32 value) {
  equips_.Set(index, value);
  // @@protoc_insertion_point(field_set:Msg_RoomPlayerInfo.Equips)
}
inline void Msg_RoomPlayerInfo::add_equips(::google::protobuf::int32 value) {
  equips_.Add(value);
  // @@protoc_insertion_point(field_add:Msg_RoomPlayerInfo.Equips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Msg_RoomPlayerInfo::equips() const {
  // @@protoc_insertion_point(field_list:Msg_RoomPlayerInfo.Equips)
  return equips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Msg_RoomPlayerInfo::mutable_equips() {
  // @@protoc_insertion_point(field_mutable_list:Msg_RoomPlayerInfo.Equips)
  return &equips_;
}

// -------------------------------------------------------------------

// Msg_BroadRoomNotify

// repeated .Msg_RoomPlayerInfo PlayerList = 1;
inline int Msg_BroadRoomNotify::playerlist_size() const {
  return playerlist_.size();
}
inline void Msg_BroadRoomNotify::clear_playerlist() {
  playerlist_.Clear();
}
inline const ::Msg_RoomPlayerInfo& Msg_BroadRoomNotify::playerlist(int index) const {
  // @@protoc_insertion_point(field_get:Msg_BroadRoomNotify.PlayerList)
  return playerlist_.Get(index);
}
inline ::Msg_RoomPlayerInfo* Msg_BroadRoomNotify::mutable_playerlist(int index) {
  // @@protoc_insertion_point(field_mutable:Msg_BroadRoomNotify.PlayerList)
  return playerlist_.Mutable(index);
}
inline ::Msg_RoomPlayerInfo* Msg_BroadRoomNotify::add_playerlist() {
  // @@protoc_insertion_point(field_add:Msg_BroadRoomNotify.PlayerList)
  return playerlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Msg_RoomPlayerInfo >*
Msg_BroadRoomNotify::mutable_playerlist() {
  // @@protoc_insertion_point(field_mutable_list:Msg_BroadRoomNotify.PlayerList)
  return &playerlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Msg_RoomPlayerInfo >&
Msg_BroadRoomNotify::playerlist() const {
  // @@protoc_insertion_point(field_list:Msg_BroadRoomNotify.PlayerList)
  return playerlist_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fCopy_2eproto__INCLUDED
